version: "2"
services:
  svnstatus:
    image: shukriadams/svnstatus:latest
    container_name: svnstatus
    restart: unless-stopped
    environment:
      svnurl : not-set
      svnuser : not-set
      svnpassword : not-set
    ports:
    - "7101:3100"
